import type { Producto } from "@/types/producto";

export const productosDemo: Producto[] = [
  // MANDINGAS
  {
    id: "especial",
    nombre: "ESPECIAL",
    descripcion: "Papas, chorizo y salchichas",
    precio: 6000,
    imagen: "/productos/especial.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longipapa",
    nombre: "LONGI PAPA",
    descripcion: "Papas y longaniza",
    precio: 10000,
    imagen: "/productos/longuipapa.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longui-especial",
    nombre: "LONGUI ESPECIAL",
    descripcion: "Papas, longaniza, huevo, chorizo",
    precio: 11000,
    imagen: "/productos/Longuiespecial.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longui-pollo",
    nombre: "LONGUI POLLO",
    descripcion:
      "Pollo desmechado, longaniza, 2 salchichas, chorizo coctelero y huevo",
    precio: 17000,
    imagen: "/productos/longuipollo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "supermandinga",
    nombre: "SUPERMANDINGA",
    descripcion: "Papas, huevo, chorizo, salchichas",
    precio: 9000,
    imagen: "/productos/Supermandinga.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandiburger",
    nombre: "MANDIBURGER",
    descripcion: "Papas, carne de hamburguesa, arepita, queso",
    precio: 11000,
    imagen: "/productos/mandiburguer.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo",
    nombre: "MANDIPOLLO",
    descripcion: "Papas, bombon de pollo, huevo y arepita",
    precio: 12000,
    imagen: "/productos/mandipollo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo-desmechado",
    nombre: "MANDIPOLLO DESMECHADO",
    descripcion: "Papas, pollo desmechado y huevo",
    precio: 11000,
    imagen: "/productos/mandipollodesmechado.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo-especial",
    nombre: "MANDIPOLLO ESPECIAL",
    descripcion: "Papas, pollo desmechado, sachicha, chorizo coctelero y huevo",
    precio: 13000,
    imagen: "/productos/Mandipollo_especial.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "jumbopollo",
    nombre: "JUMBOPOLLO",
    descripcion: "Papas, bombón de pollo, huevo, chorizo coctelero y arepa",
    precio: 14000,
    imagen: "/productos/Jumbopollo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longuijumbo",
    nombre: "LONGUIJUMBO",
    descripcion: "Papas, longaniza, huevos, chorizos cocteleros, salchichas",
    precio: 13000,
    imagen: "/productos/Longuiyumbo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "tocipapa",
    nombre: "TOCIPAPA",
    descripcion: "Papas, tocineta, queso y huevo",
    precio: 13000,
    imagen: "/productos/tocipapa.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "tocipollo",
    nombre: "TOCIPOLLO",
    descripcion: "tocineta, pollo desmechado salchicha y huevo",
    precio: 17000,
    imagen: "/productos/tocipollo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "choriternera",
    nombre: "CHORITERNERA",
    descripcion: "Papas, chorizo de ternera",
    precio: 11000,
    imagen: "/productos/Choriternera.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "choripollo",
    nombre: "CHORIPOLLO",
    descripcion: "Papas, chorizo de pollo, arepa",
    precio: 11000,
    imagen: "/productos/choripollo.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "carne-desmechada",
    nombre: "CARNE DESMECHADA",
    descripcion: "papitas, carne desmechada huevo.",
    precio: 14500,
    imagen: "/productos/mandidesmechada.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandimixta",
    nombre: "MANDIMIXTA",
    descripcion:
      "Papas, carne desmechada, pollo desmechado, salchicha, choricito, huevo",
    precio: 18000,
    imagen: "/productos/mandimixta.webp",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // RAPIDAS
  {
    id: "hamburguesas",
    nombre: "HAMBURGUESAS",
    descripcion:
      "Pan artesanal, carne, queso, tocineta, ensalada, cebolla caramelizada y ripio",
    precio: 15000,
    imagen: "/productos/hambuerguesa.webp",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "perrito",
    nombre: "PERRITO",
    descripcion: "Pan, salchicha, queso, tocineta, ensalada",
    precio: 10000,
    imagen: "/productos/perro.webp",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // PATACONES
  {
    id: "patacon",
    nombre: "PATACON",
    descripcion: "queso, tocineta, pollo desmechado, ensalada",
    precio: 15000,
    imagen: "/productos/patacon.webp",
    categoriaId: "patacones",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "patacon-mixto",
    nombre: "PATACON MIXTO",
    descripcion:
      "queso, tocineta, pollo desmechado, carne desmechada, ensalada",
    precio: 18000,
    imagen: "/productos/pataconmixto.webp",
    categoriaId: "patacones",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // GASEOSAS
  {
    id: "gaseosa-coca-cola",
    nombre: "GASEOSA COCA COLA 400ML",
    descripcion: "Presentación 400ml",
    precio: 4000,
    imagen: "/productos/gaseosa_coca_cola.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-coca-cola-1-5",
    nombre: "GASEOSA COCA COLA 1.5",
    descripcion: "Presentación 1.5L",
    precio: 8500,
    imagen: "/productos/gaseosa_coca_cola1.5.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-colombiana",
    nombre: "GASEOSA COLOMBIANA 400ML",
    descripcion: "Presentación 400ml",
    precio: 4000,
    imagen: "/productos/gaseosa_colombiana.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-manzana",
    nombre: "GASEOSA MANZANA 400ML",
    descripcion: "Presentación 400ml",
    precio: 4000,
    imagen: "/productos/gaseosa_manzana.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-naranjada",
    nombre: "GASEOSA NARANJADA 400ML",
    descripcion: "Presentación 400ml",
    precio: 4000,
    imagen: "/productos/gaseosa_naranjada.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-uva",
    nombre: "GASEOSA UVA 400ML",
    descripcion: "Presentación 400ml",
    precio: 4000,
    imagen: "/productos/gaseosa_uva.webp",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
];
