import type { Producto } from "@/types/producto";

export const productosDemo: Producto[] = [
  // MANDINGAS
  {
    id: "especial",
    nombre: "ESPECIAL",
    descripcion: "Papas, chorizo y salchichas",
    precio: 6000,
    imagen: "/productos/especial.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longi-papa",
    nombre: "LONGIPAPA",
    descripcion: "Papas y longaniza",
    precio: 10000,
    imagen: "/productos/longuipapa.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longui-especial",
    nombre: "LONGUIESPECIAL",
    descripcion: "Papas, longaniza, huevo, chorizo",
    precio: 11000,
    imagen: "/productos/Longuiyumbo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longui-pollo",
    nombre: "LONGUIPOLLO",
    descripcion:
      "Pollo desmechado, longaniza, salchichas, chorizo coctelero y huevo",
    precio: 17000,
    imagen: "/productos/longuipollo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "super-mandinga",
    nombre: "SUPERMANDINGA",
    descripcion: "Papas, huevo, chorizo, salchichas",
    precio: 9000,
    imagen: "/productos/mandimixta.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandiburger",
    nombre: "MANDIBURGER",
    descripcion: "Papas, carne de hamburguesa, arepita, queso",
    precio: 11000,
    imagen: "/productos/mandiburguer.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo",
    nombre: "MANDIPOLLO",
    descripcion: "Papas, bombon de pollo, huevo y arepita",
    precio: 12000,
    imagen: "/productos/mandipollo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo-desmechado",
    nombre: "MANDIPOLLO DESMECHADO",
    descripcion: "Papas, pollo desmechado y huevo",
    precio: 11000,
    imagen: "/productos/mandipollodesmechado.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo-especial",
    nombre: "MANDIPOLLO ESPECIAL",
    descripcion: "Papas, pollo desmechado, sachicha, chorizo coctelero y huevo",
    precio: 13000,
    imagen: "/productos/Mandipollo_especial .svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "jumbo-pollo",
    nombre: "JUMBOPOLLO",
    descripcion: "Papas, bombón de pollo, huevo, chorizo coctelero y arepa",
    precio: 19000,
    imagen: "/productos/Jumbopollo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longui-jumbo",
    nombre: "LONGUIJUMBO",
    descripcion: "Papas, longaniza, huevos, chorizos cocteleros, salchichas",
    precio: 13000,
    imagen: "/productos/Longuiyumbo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "tocipapa",
    nombre: "TOCIPAPA",
    descripcion: "Papas, tocineta, queso y huevo",
    precio: 13000,
    imagen: "/productos/tocipapa.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "tocipollo",
    nombre: "TOCIPOLLO",
    descripcion: "tocineta, pollo desmechado salchicha y huevo",
    precio: 17000,
    imagen: "/productos/tocipollo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "choriternera",
    nombre: "CHORITERNERA",
    descripcion: "Papas, chorizo de ternera",
    precio: 11000,
    imagen: "/productos/choriternera.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "choripollo",
    nombre: "CHORIPOLLO",
    descripcion: "Papas, chorizo de pollo",
    precio: 11000,
    imagen: "/productos/choripollo.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "MANDIDESMECHADA",
    nombre: "MANDIDESMECHADA",
    descripcion: "papitas, carne desmechada huevo, salchicha, chorizito",
    precio: 18000,
    imagen: "/productos/mandidesmechada.svg",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // RAPIDAS
  {
    id: "hamburguesas",
    nombre: "HAMBURGUESAS",
    descripcion:
      "Pan, carne, queso, tocineta, ensalada, cebolla caramelizada y ripio",
    precio: 15000,
    imagen: "/productos/hambuerguesa.svg",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "perrito",
    nombre: "PERRITO",
    descripcion: "Pan, salchicha, queso, tocineta, ensalada,",
    precio: 10000,
    imagen: "/productos/perro.svg",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // PATACONES
  {
    id: "patacon",
    nombre: "PATACON",
    descripcion: "queso, tocineta, pollo desmechado, ensalada",
    precio: 15000,
    imagen: "/productos/patacon.svg",
    categoriaId: "patacones",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "patacon-mixto",
    nombre: "PATACON MIXTO",
    descripcion:
      "queso, tocineta, pollo desmechado, carne desmechada, ensalada",
    precio: 18000,
    imagen: "/productos/pataconmixto.svg",
    categoriaId: "patacones",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // GASEOSAS
  {
    id: "gaseosa-coca-cola",
    nombre: "GASEOSA COCA COLA",
    descripcion: "Gaseosa Coca Cola",
    precio: 4000,
    imagen: "/productos/gaseosa_coca_cola.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-coca-cola-1-5",
    nombre: "GASEOSA COCA COLA 1.5",
    descripcion: "Gaseosa Coca Cola 1.5",
    precio: 8000,
    imagen: "/productos/gaseosa_coca_cola1.5.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-colombiana",
    nombre: "GASEOSA COLOMBIANA",
    descripcion: "Gaseosa Colombiana",
    precio: 4000,
    imagen: "/productos/gaseosa_colombiana.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-manzana",
    nombre: "GASEOSA MANZANA",
    descripcion: "Gaseosa Manzana",
    precio: 4000,
    imagen: "/productos/gaseosa_manzana.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-naranjada",
    nombre: "GASEOSA NARANJADA",
    descripcion: "Gaseosa Naranjada",
    precio: 4000,
    imagen: "/productos/gaseosa_naranjada.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "gaseosa-uva",
    nombre: "GASEOSA UVA",
    descripcion: "Gaseosa Uva",
    precio: 4000,
    imagen: "/productos/gaseosa_uva.svg",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
];
