import type { Producto } from "@/types/producto";

export const productosDemo: Producto[] = [
  // MANDINGAS
  {
    id: "tocipapa",
    nombre: "TOCIPAPA",
    descripcion: "Papas, tocineta, queso y huevo.",
    precio: 13000,
    imagen: "/productos/tocipapa.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "tocipollo",
    nombre: "TOCIPOLLO",
    descripcion: "Tocineta, pollo desmechado, salchicha y huevo.",
    precio: 17000,
    imagen: "/productos/tocipollo.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "choripollo",
    nombre: "CHORIPOLLO",
    descripcion: "Papas, chorizo de pollo.",
    precio: 11000,
    imagen: "/productos/choripollo.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "longuipollo",
    nombre: "LONGUIPOLLO",
    descripcion: "Pollo desmechado, longaniza, salchichas y chorizo coctelero.",
    precio: 17000,
    imagen: "/productos/longuipollo.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandiburger",
    nombre: "MANDIBURGER",
    descripcion: "Papas, carne de hamburguesa, arepita y queso.",
    precio: 11000,
    imagen: "/productos/mandiburguer.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo",
    nombre: "MANDIPOLLO",
    descripcion: "Papas, bombón de pollo, huevo y arepita.",
    precio: 12000,
    imagen: "/productos/mandipollo.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandipollo-desmechado",
    nombre: "MANDIPOLLO DESMECHADO",
    descripcion: "Papas, pollo desmechado y huevo.",
    precio: 11000,
    imagen: "/productos/mandipollodesmechado.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandi-desmechada",
    nombre: "MANDI DESMECHADA",
    descripcion: "Papitas, carne desmechada, huevo, salchicha y chorizo.",
    precio: 14500,
    imagen: "/productos/mandidesmechada.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "mandi-mixta",
    nombre: "MANDI MIXTA",
    descripcion: "Combinación de carnes con papas, huevo, salchicha y chorizo.",
    precio: 18000,
    imagen: "/productos/mandimixta.png",
    categoriaId: "mandingas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // RÁPIDAS
  {
    id: "hamburguesa",
    nombre: "HAMBURGUESA",
    descripcion:
      "Pan, carne, queso, tocineta, ensalada, cebolla caramelizada y ripio.",
    precio: 15000,
    imagen: "/productos/hambuerguesa.png",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },
  {
    id: "perrito",
    nombre: "PERRITO",
    descripcion: "Pan, salchicha, queso, tocineta y ensalada.",
    precio: 10000,
    imagen: "/productos/perro.png",
    categoriaId: "rapidas",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // PATACONES
  {
    id: "patacon-mixto",
    nombre: "PATACÓN MIXTO",
    descripcion:
      "Patacón con combinación de carnes, queso, tocineta y ensalada.",
    precio: 20000,
    imagen: "/productos/pataconmixto.png",
    categoriaId: "patacon",
    gruposAdicionesIds: ["salsas", "adiciones"],
  },

  // BEBIDAS
  {
    id: "coca-cola",
    nombre: "COCA-COLA",
    descripcion: "Gaseosa Coca-Cola 400 ml.",
    precio: 4000,
    imagen: "/productos/coca-cola.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "coca-cola-15",
    nombre: "COCA-COLA 1.5L",
    descripcion: "Gaseosa Coca-Cola 1.5 L.",
    precio: 8000,
    imagen: "/productos/coca-cola1.5.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "colombiana",
    nombre: "COLOMBIANA",
    descripcion: "Gaseosa Colombiana 400 ml.",
    precio: 4000,
    imagen: "/productos/colombiana.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "manzana",
    nombre: "MANZANA",
    descripcion: "Gaseosa Manzana 400 ml.",
    precio: 4000,
    imagen: "/productos/manzana.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "naranja",
    nombre: "NARANJA",
    descripcion: "Gaseosa Naranja 400 ml.",
    precio: 4000,
    imagen: "/productos/naranja.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
  {
    id: "uva",
    nombre: "UVA",
    descripcion: "Gaseosa Uva 400 ml.",
    precio: 4000,
    imagen: "/productos/uva.png",
    categoriaId: "gaseosas",
    gruposAdicionesIds: [],
  },
];
